# Default values for acceleration-a.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  accelerationaImage: acceleration-a #For local docker images
  accelerationaTag: latest
  pullPolicy: Never #For local docker images

deployment:
  port: 3002
  protocol: TCP

vars:
  WEB_PORT: 3002

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3002
  protocol: TCP

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
