apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "acceleration-calc.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "acceleration-calc.name" . }}
    helm.sh/chart: {{ include "acceleration-calc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "acceleration-calc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "acceleration-calc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.accelerationcalcImage }}:{{ .Values.image.accelerationcalcTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $val := .Values.vars }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
          ports:
            - name: app
              containerPort: {{ .Values.deployment.port }}
              protocol: {{ .Values.deployment.protocol }}
          livenessProbe:
            {{- include "acceleration-chart.liveness" . | nindent 12 }}
          readinessProbe: 
            {{- include "acceleration-chart.readiness" . | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
