{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "acceleration-calc.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "acceleration-calc.name" . }}
    helm.sh/chart: {{ include "acceleration-calc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ include "acceleration-calc.name" . }}
              servicePort: {{ .Values.service.port }}
{{- end }}
