apiVersion: v1
kind: Service
metadata:
  name: {{ include "acceleration-dv.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "acceleration-dv.name" . }}
    helm.sh/chart: {{ include "acceleration-dv.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.port }}
      protocol: {{ .Values.service.protocol }}
      name: app
  selector:
    app.kubernetes.io/name: {{ include "acceleration-dv.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
